apiVersion: v1
kind: Secret
metadata:
    name: discord-template-notifier-secret
stringData:
    config.toml: ENC[AES256_GCM,data:VqadrOmmkpzJheUkliJVpAo+A3MNoDsyw9E6XHFRimcpQuQ0Xp4+gYg/AuEvk4WVixJdbsOdusv6omX3/9NtLdj3cAiHiYQLOYzWVzoyHMacG4X7RFD82EMeTMsXMmukIGhhleNQiqz+SE7SdG/vQrQ1gDWVjokD7Di5YPhtHj+PPcWHsO6jyraC+98d2+0DGu/dTG2h4Qose/W73ZrZq24MSykRBXHl4hvLjIitKUhvOFYevb8q1LhbanjRiHkk+MgDGdk1wfjT9qS3bT+f3ROjnZjZCrtzXBTstFU363opWQJoePz5YAklUKeLBgGF1Wn5U/NrgWh2P3b7NKFqYON8RfXMmh440m7A7DfgHjCDvhUvVzp6VxvrXvvbAzjxig==,iv:AobB/+YEY+98WPiw0XHuL+2EkYXH+IDkLCz5eBwL3QY=,tag:P0ySD3Isahg9Bw/PHNqIYw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORm84VXFLQXpEdzRRNE9q
            Rm4wT0FUeVg0NnA5cjhOUFZYN3VYVUVUQlZNCnBEVU5SZSs5WWRrQUYxLzQ0UEdW
            NEd3OHlZUWg5djFvYVlFRXl1WTFiYjgKLS0tIFhzYTVaV3NEVEw3Rit1ZE1ZY1JJ
            SVhDcUFha1U2RndCdHpTQmg2ZkJCY0EKFmpzb00HW/MyaX0vNtTEKQGt8+luRjwm
            JpIoCz4BSmA/k1UyDsbKIvze4wE97ozjq3A/HLWIUa/Zta/rk0Jx8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-29T00:51:49Z"
    mac: ENC[AES256_GCM,data:QCMeupzGzYCu4WCRMVTIUVWO2NDH5on0DWAl9fZiIdl62QUGIQuj8wQ6BqTuFlA2OnuxZdHp+sSv966XRPcjk0FDuGKkDWiCKbHxFoizFQZ/gAVruxkC6ieKPOnGJ7lm/DfzAXAm1gLRMtXBNWMhVzHhMUKAQ0fS4sCwcCGjOCM=,iv:UiUL9JeU0YG5ms058VSIahYIXCM5FxTfYmw5OAczKlo=,tag:lJAH3ZMXoJ1yO1lzC4E0Iw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
