apiVersion: v1
kind: Secret
metadata:
    name: discord-template-notifier-secret
stringData:
    config.toml: ENC[AES256_GCM,data:IeYFqusNNCZij5F3udNPaa1eat5378anIegXvITQbU6cwbCDSMLJ7DGcCD66IE5pckLh2nvtsYXsClJCcxfAA5la7LXqweKWZW/XjgjD091v9sDXSBne0PxMDKHzk+oQUj7e0lJ3ik1FByIbki6YNY1dDpFJ1NDCknIrjyjEswTYdLRJM4UekXoLrhUSZQJH75C2fESQjoYoXBzOmH84MdQNdovWg8hIAa7PTdiz+W+gtXYkDd3wdRZ7O9M3YIdXMdQadn2mR6KLvBTTLEvnTIxTv9Iar36fsY62hCmquu1l5uDXDTGzUOIY4a94SP93Qo4aqDDlUaugSYUW0wDL+8u7aeJt6T0rdRim9RO0HRGNqDKV0UHyKIBLIpU2dFXOhA==,iv:jL4hHjOTy4QqlGvrQ3dcEo1yyHlWlqgKuYe9VCscUlc=,tag:3lN5zTWXkDqrtZXeTtikLA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSnhOZEZOai8wVXBVL1ZN
            QVozZ0lDY3djZnkydysyUDQzT0h5TjY5SVFJCkRETWovM0VaYTd1WDU0dDNGZG5J
            NUR6b1lpQ28ybWc2RDlocjE0bGw1MFUKLS0tIFhOL2dqY1dScStXdzZ0UVViTi9J
            c0E1bW5kczdEQjdwMEozMDQ3WHhmVFUKw72iqMC8cxE60VyAdpazQ26lzSCyZmv8
            FtkmZscM/fA5pjg5wyKE2XRI/J7U7CW/nU1a24Jn6sAi3o0ceRlx7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T04:23:08Z"
    mac: ENC[AES256_GCM,data:ogaOtcljx5JG3YMH1DkQNPQ73fRSZ9Hfpp9HBA4L2OKWc44EwQVoFU/EWYjkS3KWD02o2Q9AB7ypPy+qFAXkaC214RNS4VRo5+3pMb6UXksUVX5MvmoFPkMaobfgzOIblLuZ91x6l0BdS9kuehymU6plv9gUQuITR0Lo5B1vgh4=,iv:shEazhwTLL03cj49mpWQINUTQcdG3ZG5CnWzuO33OWA=,tag:Nz48WGXvN06VYQsJrzX3Sw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
