apiVersion: v1
kind: Secret
metadata:
    name: discord-template-notifier-secret
stringData:
    config.toml: ENC[AES256_GCM,data:9gLJpSKxjIYT8Gf8mULxxspszhWC1CI0IglWKqhaLfs95Gt1eA3H16c8ttS7gn7YIxwxfPIER+AZUl+urWQ2i0T3ulqCIDbH8iLRi0ZHeAkghsN7bA4VV4NE5qM0Eb20rMxa+ZhbRh5ZwgdfWKUkvHo4b5aQW8mOLH/P/kSlGiT+pIc8nQZ2fpeW+oP7XJqbiVQam82rNngMLF0hiAkLm/nqFij4pvSmnxP/7RYq2yuFTPaif3j3Ls4+D178LJ1A5T0R0MHqqBnrBTP/joOkRV6CXGJhuYZ3ZS2GeuXfqTNCHRCNGRCUsbYaW2mnYvCuw+0evak2/zvyzGuhDXcVzqJyDNwIPcwwwD0IyADJvi1nKXWCpElcE7tfJf46QLndhw==,iv:pK58bwUHaZRGGJJWpGgWzts/uAcEtxE24Ihg+HmL4wU=,tag:JnbLltMfIns9X8Lhk0cXOQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjeGdDOFp6NXJKbS9ONEgv
            QUFPTUZVR0FiV29XY1AvZ211MzdVaHN5ZjA0Cko2VjhFWTRHOVhqTmNNUzlSRDdq
            ZGh1YlRBZWxnazF3cmVLcGNkZ0I4ak0KLS0tIFAva0lxQWJGcUlzODdlUjI2ZTF3
            MklYNlNFdTdYMnhZRHF4WFFrTWhJa1UK2iT0CVAklk9GYyEbBsaAmyPBb2VVbMbM
            XZ++qcpTVTYQ1KYtva6FlKS3U9fuGdHErbwIJrc3q7m1Fu/o1IZrdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-26T03:59:04Z"
    mac: ENC[AES256_GCM,data:AHbubDW4YbEVqgIFU90yzdWM+CEU+CbVdXXM5stbP9RLZPu+eqCHLCbnh/lcWzYemr3pYVn4FrXWHSPMD4g0zJjKYBUmtq7h5QNFKE3aY8utwfQWpyK6cYP47dR0kzLPR8cp/7DymbTnD+uNT1evPJfAwV+A5b2LVgVzIgJnrAA=,iv:+E8kehTIHdrJnIdi08teV3gWgB5UTNjR46VsBaPROb4=,tag:YWQBE9PS76gxLTtZgxM3Rg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
