ansible_become_pass: ENC[AES256_GCM,data:n+e1p1ncwfHL,iv:t1F0teoiFGiUA+tC8PVBCyap5+pf8oGXDVaFmLPbRsk=,tag:o4KZdTktYVRaFY7WJKbJZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTk56Q01zTWw2NU0ya1NS
            VEFhTkZNMmxaRnFZRDlTRmNwaEJxUVdld2d3ClhQSGRORkFrWDIzaVEyZVdtdnM3
            YnkzK2l0dkZaNGl6aDFKb3RnWmRLNXMKLS0tIDhxWU1Gdm1BVU8vdFVlQ0h0QWxV
            dkozb1hDV29RYWcrb21XU1U5dlBOV1UKBiGtFfxnembPgoFEqOxi1wOM/mZb0Ts0
            1O/r0YP4qyQyM7fAFB5yhF8sQG1hJTj4mwvClbI9lo6XA1FxtayrYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T07:09:55Z"
    mac: ENC[AES256_GCM,data:0kWdtq7+85ghm2DJYzabyqLpeXiO8uigCmgEw55fTB53HDKsMA+6TqbOI2GxgCd9M21ZvyAsDvh3esyQB6iFUCNRKdMnWSwNeu1z2vOGbJ0JpjZJg9rGDGDkB0NWra+X3x1Mj67tGEc+SB7Dk80jN9Psew65QpIxuOJyvNqASVk=,iv:RGzXGuKJKRrCcmEbvbtm2bOm+AxI5QSRgN9ezOxrNxw=,tag:bOXJQ8l92cJIIiNR1SM8MA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
