ansible_become_pass: ENC[AES256_GCM,data:Aq/GRjgKiUnr,iv:J9S8W3/0yrbvJrE5F9villL4d6qCkSvR6q6uM7zlcMw=,tag:A3PwbGui0rS0rd4B5pP4Yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTUtQYmlNRmdieGdvWHBz
            RDhyY1JTdXoyNlFhSmtUc01iMFlCbUVMNFF3ClhTZUIwY0Z1TjFyZlFYV21rdFp0
            Q25pOXlSdk5IVHZUdmJ0elcvR05zdjgKLS0tIFNNcTR1TW9kNjIzMERmQ21xcjAr
            S05zZmJmYUhKWDdCUytIZ3o2cktsdU0KFJsQXc5mQqnok8yaG7t84Rk4riU0p9LT
            A7adXKc+YLJCmjdIEOmUL0KxPDnpTBuvQM076lbbvTLU01XYrlR9JA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-29T00:51:17Z"
    mac: ENC[AES256_GCM,data:1g7uMQ3O/tYWxK2/baoRjLJmS/+kvd8yBtZK2Ebo31ljE4/8yYIjYY1suMGpz4KQD4Wmyl9MqtVKpJKkkPCfxeldSaH2obxonakQMDJQEf7g5V/AIgIFAh9mv/xG8pV+ojH7FcRHQ1pD05bBJ2by6S04Zn65I+MSu0PvKwM4YYQ=,iv:JS1hcwdgMzx77xDMBIUgW/7B/D8XT18YAnKlCkEYCig=,tag:CBsLKcHyk4A3Bx/IP8VLdg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
