ansible_become_pass: ENC[AES256_GCM,data:5wGoDDSFBq6W,iv:vJAJO09Siro0npxpVTRM8rFgrzC816zoLtQLcDfPFHg=,tag:XA5Crc3JWP1Z9u9Y1Dl1yA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NG1ZQ0h6WVhmUzc2ZnB2
            K3dybkNDaUFhQmJ1dFdtbGI4bzBXOUtlNGxVCnROeDh0V0pSY3l6VHh3cHVjb2xr
            UEducVhGTCtRM0o3R2ltU3hKK0k2a1EKLS0tIEM0ZVNTcUdDWHVadlBIeEk4V0xr
            NkZZZ1h0N0ZoSTh0TWRraXdVNVlVT3MKQNmhSQMF7/7WHN2AZwrLVFJoyfSslM8P
            652l2cWBU7+xNhWtjrT0uAX68VZ7qBJO5eny2yf1V4ajSK4QOjrPJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T04:22:32Z"
    mac: ENC[AES256_GCM,data:WJXaiNmsEIc0Ue41YA7CzKAcgGsxfgMjzGPUStqqaRCwTGmMJe/5Py7vwwCa/vpwtcS6IamNnvTuUAVQkMpcL1fM/LAgXX3x7HSDKXhKtPFtEMvdDZNOiLooB2Xx8+K+EzlKKuoiu4NN0ij7vkpedM9HNX2genyR5x5ApGLl+fU=,iv:tRF4xrdj+pGWI7F+OV9E/FMjJ98LtWzgo65upgdLxGI=,tag:dmEwMDbiZRpAUIKOYjswkA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
