apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:bNxxiTe1CsQ8Q9XpETXQY2ughb4292oY+fqzDILE9I0rZXTQ,iv:qKr/zFtvIx0THpo0MwE5RbpK4FXNzjLLsK5thYhx7No=,tag:A2uq9Tppsj+G7q93GG2bjg==,type:str]
    credentials.json: ENC[AES256_GCM,data:s1MhEDKTkFUuya+B9TGHTTSYgLGKMpGAaBDvajMVYFBE1Ja2eim16NJJS9586mRSoE1hNlTZMiJjgF72WtdaHFyu9x6s3COXT8pTT6h+ir/a2drKY9AFmD4Lg0Nskj5VW5SBfpL7nHkClwIpaWgkJOFlREvk5LOs3+uBopp4b1iAF7NnXDGtS6K36XyQqTBGJHjLwRC4M4cxBskIz24hXcjrvSGRiJ30WbPG4Mcigw==,iv:Y7b2G1MsspkpHf4mH8l2DWAz70/MOoUGw25U0rm8tpc=,tag:JChGqO167ZX2LZA5OcUyEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RDU0TnZoSmF4eDZMSDVM
            OXc1Slg4RWNUNjRZK05kYnJ3VjhYcEtJbVFVCklxb3RTK2hhSXdzWmlhQzZMZnh1
            ZGx3aTFQOFBoVFg0eGVFV0krMHl4dWsKLS0tIDZSbjM5ZituaTMwRVJtaFVWVWJa
            Q1BwYjFsNUlKY0ZMNUVJMDFhK0xRMFkKrkD87BSamX7QgH6ic1mSr03P/WoHLM+l
            KVqzJRS8wSk3hJxZMAlkgK48LNDWWUvqw0e+U0oQbC+KtjvmTJWnbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T07:10:27Z"
    mac: ENC[AES256_GCM,data:MsVtBGV+x22MYY1e95TdZxcZen+KTC4crCxl7mLlJSWKOSjAuGJqXnCKGUd8/Bb0UyJIIUOy3/363Y43xC4RSV1ydLnBKtivxD/xb4NBJfbRRoy4rwfVR5wF3zlZ6PN/8Lu2CHe3GrNHeRgx45+emKm+5ebknWfHxgnO0ksh9F0=,iv:g4rBkIm6ZmIFUKCaGXeV7qzATLDrfKsBxzofRI+ybK4=,tag:b3NV+RwyFKsbzKL97FIy/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
