apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Uk6nsRWE6V4JqaG3tU2Cg0BU1IqlqxnRLkTTZHjG2j+Txdc+,iv:fqHMcZENkycEpB5ojLpWdr52gkYcPwYcXt2fUnKtNHU=,tag:U0PbcNvCpQe87miHZd9hkQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:MCC8CeGxySUcm2xMCXaLDiD2Jbw4cxkhcZiPWXY+Lv4qcp6mvqG4pr8K61VAbGrfsJc7oDmScrvl9C+E9qv/3vhIViSJ4g9HPx8MPrWedbdgxBTDKqMOJBwX0sDdSr+kh9j42jvfM+jMku04h6gsmCsYP1/Z2dDhPbV21VMGf+AKAAc8Km8Ef2wGAiQh4gBm/nR8oET0yavEkYsy0ZMqQCGf+Y1g39BbvLnHmtYg3g==,iv:l5JS7gWMtQnRBQVSgPHMgaFljfHF37XmV9+HJ/kIh74=,tag:zUoWMCJDCP91kXptbJHf2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOb1poL2l2djFYOTRWZ1ZI
            dXFuc2tPVVdBcXZKeG51bXQxWU91RDYzTFJFCkd2d1gwRFg3MEpyckVrWTk0eDJW
            a0hEODFDTUMwRlhGQWNQcHQ1RDdTSlEKLS0tIFlKbU04cmt4enVPcTlnaS9Tb3dj
            MElTOXN1RUllV1lQNHkrcHNUR2w2NzgKeh377pLzG2mykskTFWuLoDujm2o82by3
            f0Iv8ymOgv7d/qnNpQNxLMnKXxiNTzW++qGkYp/WgiAHgKl8WqfnCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T04:23:03Z"
    mac: ENC[AES256_GCM,data:K7MgCth/nEYZ54bXNVzL3hGUExOGKScu7EL7DrM6YCFz1ID4cVDHytmxuJfapGkwg1/ZMr0JTTtle4Ur6djk8HpuDhwIKHNP7jkmdnulP181XvPD5AnjqugPrJCtdsudVq4mDz/eTiozeTrYV1s5M2ptXLSV10eS15EhzjZRSuM=,iv:k/ncTz00CgShbY/5SPCtKM3Kcz8WFRBDDbhVK8kNlJg=,tag:BM1lV5TXgt6Ij6O2kNiOQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
