apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:PmEFU0H7aiPi2Ibw9R1fEBSbKgxSlZvf,iv:513PLAN+KM3FVvnRHhU5Vf9RFTk7Gp7pRiWceDT7dCA=,tag:Nb+toSAc5TNeB3+hiEjP/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZnE4V3Y2eTk1Mm1qbmtI
            UG9aUXFaK2xQdDRIZnQ4MmVhVEtLR203S3g0Cm8vS2hZbVd0cUYzdW16RkluUW5V
            Vy9FUjN2N1lxTXlDWG1UMVEwUXE4Um8KLS0tIFJxUTlacjczWm95WGxlK3N4enJt
            czZBVDRKSlFHNXFpNTg0TmdNZkpacDgKezCI/qrE+b/8SQqAY+ppajTgpjjloz5I
            xGQ2B1KqQ7GaQ/kP7RNRC2jKDVoc9rYSfzAU6/nh+16TlnuKNn8sPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-26T03:58:58Z"
    mac: ENC[AES256_GCM,data:JS4pr8Fk4yffiZ0O1wPorDokW3ZHL4RFZG8naNC09Wy83QOY8VBoG4SHf7V2RIeTjgIBPfca2CIpDd1xojJtCSR3hcbTvscRrnG+23oVmWr90glQgiUEvYqYfMfxOS2nT2axdyjST2vmJK4zL3G4gf/34Hg8aEeCy2HIxz+4ulU=,iv:kGJFLOHaUF6nqTegL9T/wlpnlmpTENnYAPhHhoUlNI8=,tag:9y3kdP3cQWkLxmc9x1Ayyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
