apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:RWxxzjabJL592QQGmi1QUsAMcTOx2ObS,iv:B312kuVpnWpwLu2Jqr89Q4LebnJnj4ayJYYh2+HqFyQ=,tag:Wsgw/hGq1gxrVBpdGHy4LQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQmRKWUo5d1J0aWhTbUR3
            R0xrVEhuZ1FCbkh0c0RjUldRLzN2VEdSaEZVCktrSmxBd2pSYmhac0VXanhLWUk2
            Um1nUnpOMnpaVXNqSCtJSktVV3g5bVUKLS0tIDllWWhZRWtGelhmM2RWQzJPMmVh
            N2laMGhISWpjVmw3TE5LdHkwcWhxMDQKmLBoFa1cbrL+9YQvXNhf1DkKwsHYru8d
            mwJpV6Ot1nqAK0oEuv8BGEyKDLgmNtKAsPJe5nuEN8fG+bJjpZhL7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-29T00:51:46Z"
    mac: ENC[AES256_GCM,data:kezODiE2dQ4HDzjsNB/EmAOiWZ0CGrOLLpPU4alPIHr4p+iFf75pSeN0jRABdA8MY2pa9MDN8u3/zDOQwDwZCQTDmILSq+W17OpC9MD0Hox4sR+yYrjlHQFiUP6asdTCcZ2VlZPasimcGltwKiDZTmwq/nOtPiYKQDZ5BZPHfdc=,iv:S2ty8O6YHwSkwe2K2bOIdgQFnxx5xi1SzbBkhN6G0QM=,tag:4EjhkJQ6EYnkqFSEwQq2qA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
