apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:vWC5WWGg+nM/6+iJGMINs2Hn857WNszd,iv:WVaybueM6Lpz6tm11NWER3KFhwOEaAIi1xS46VGRjNA=,tag:Icmli3hS8x0VhqnfnYbEbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDc24zd3hkRkZ3bkRoc1Ew
            Y2ptUWZvbmJXbXd4TjU3MisyWFFLZUk3Nnk0Cm9mOXJaS1h4WWJoNWRSL041VVVM
            elRVc09lalNhczJDODNHTFE1OXlKNEkKLS0tIDhYOXp3NFRReERnUDBkYTBiOWhx
            Y2w5Sk5PZkhkVktDaE8zc0pXWU1qY3MKaPpqobzyw1nmoKjytcDzFhqEeMsHOk8P
            VVLGUQF1+c+hIjRsusO7GDjADaAYtaZXbvYA6lEqx4IbPCvehIEx8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T07:10:27Z"
    mac: ENC[AES256_GCM,data:DuI1nNdftpA6T54Ra9W0SvpouFnqZoRqDeFLrXVh4uLOsXebVaNZPoXOo889zd8RsdFIJFq4827iZ/7ozPf8tupBNGwp0k2nSNj98o/NnR2h4OFFls/JZTQMMLODL59s7WMTwe+h3r5eI6OfprlnlvBhzRLnEYyaQSnQpGpXw/I=,iv:e6dLjE6eNQhOD6N8GIQSLuNlrN8A0RUr3bCGcTbzMa0=,tag:tj1a51KT0+LnHeTFPJ0t+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
