apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:H9VnM6EEFRRk8qs=,iv:+u9HW9Fh0vSCGKe1nsPCLD8mwzlNB4TLa6ZWjqAxRbc=,tag:176/Qb+3OxvlUNLNuSmWTg==,type:str]
    admin-user: ENC[AES256_GCM,data:fuINiFA=,iv:nVpLixyfp1rkmckgm+17FXPv+WPIGn/LS78AHM2TgC8=,tag:vn7nsHHDFhq3O+Sfu23E+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2U3dlenB0MTlBZ2dwUFNH
            eHNLQytLbVdPYlQ4ZHBNdXBrd3RCWG9xWlFzCkVzbnU4WUxsNTFUR3FlSHp1VG42
            MDY4T1did1YvOVN5MmNNczNoMnJmbEkKLS0tIHZFalEwK2pWVDZHVUgyWWtnOGZj
            RkdFWkRzWisrY1VUVXEzM0RSMjBZdTgK1Gm65uoMyroniGNuKw9azAS5D/trD/5a
            tVPH4yui+FyOr9rBdc968lB+TqrL9vfO7N6o/jU8HYu3ncgbDugg+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T04:23:06Z"
    mac: ENC[AES256_GCM,data:oLDbJYGyA9Qbt4iweSqBFecohb2t20AGvFbR7qWb8QE3BhdowYilBhWzbfbUo0vez6BkoDr3iOpHoa83MFdUjAtF/OU1bwz60Xm3CTPEqlhyzE/baq3dgbyrpb42a7iSVFaRn0tLSBmrYfqbswjf9E/TLCCQaopvMbSSWIQhP9U=,iv:B2gCSfX6H7zmuMyu5LmjNJlEPvQLqqzAyS68Hz9xhbk=,tag:cU6nfqQtQunuUE2ecPL6zA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
