apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:9HodmcWV8+dUNp4=,iv:Qu6ADNDk9FUiQp9oz2ReQKN+B5ZM0Ugp7ZSaTkwhPag=,tag:XdsFiCOouZ1x45QoAl9ZkQ==,type:str]
    admin-user: ENC[AES256_GCM,data:19ez4DQ=,iv:4+evkDdFQzcwA88on2Fy4JoJBzxLnsZQpkuQfC38vyo=,tag:RS97Y8u1K1kuKiIkTv2IWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOUYwdzluclVGaEpNN3Fl
            RG1NUmZ0SmZJM0xnZDUxMTdZQVU4Si9XQUZjCnhhVWt6VmtJWUFqekhBaE9va2xj
            Zy9YcmVVR0EvMHcwdHZ5SFN1KzJKeEUKLS0tIEpERWFVWU54T3pRWm1ua3NoWVRK
            NGhMdE4vTndkdlkyb21vTTl4Nk8vV0kKzDZTfTZ5etlV/0TBDcIpHZua8y8+DnEI
            Kue4qEIN6QraDon7j78NZwoOljH7fuNSnH+2z5dTG86ANbNoSHl8hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T07:10:29Z"
    mac: ENC[AES256_GCM,data:GKW1fM2U9n9jig8YruK9n4vM6LDggrRNvhLS75KAFTCfmbhc57l8jrQFz3SWEldrX64xIsW4mVan5f9vIKLv91GGqpbC59pl2fTCoByZka6VLbid26BG4WCBDjv0J+vdkgw9B23xIVzvRVpJcMJocPU6IABon2cjsQbYEJJyzJo=,iv:qs5RZjCLHumafTjgvOXIlG09YWaYwz5FyRd3e6/EApA=,tag:GhGbhG9os4qmeVcG0eR85g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
