apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ua6cy+FoOhgXSEFTNwUSbqYL0u0QfC3XfQ4Vn35JUsus+HpvdSnmig==,iv:AUu/sJLje8U/vR+SmvszxsgnMpqA8CIzxncsdOF+7yA=,tag:ZIzyrqaSU8DzgO7EzJ3/gQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzL24xL1lCekM4Wm45a2cv
            UHRCckc2MVUzejI0NHlxQ0haUW95THdaZ3ljCllPclgwWU9aaC9MNUdiSVJoMnc2
            bjFoUDdQMStYdVF5b1lVcXR3OVU4MUUKLS0tIDNxMnJqTEVJY3RKbnFPWW9pTnJK
            dVpKcnV6V0R6WFMzK2tLVmdFZ1hKbU0K72tXhm/z9YpyWc1aUW8GDu4GGB/xScrx
            mCTOKtPA6CEPUV/k13SV98C+HXaQ945CgZKGdcO0Se4mgsjNJac6Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T07:10:27Z"
    mac: ENC[AES256_GCM,data:kBBsMesLXSrYwJeSCBtqfiafWYOw9Uca/Rj/ZusfRtY9YbH1Sagq3wbm7olzySK4eSDiuclnY9I82IaNXyJWEjjxQYJuurOIcoPCokRnr8IhYl7qX1J2BgtAu2ZVMUt1YCL5/OekiGiFCxI+f1Z8Y3aYx7yWqMr26MEd1iRCATc=,iv:SMwm3wIayPytkjOJWy6UAQiY4D3tGNbh3C9UKL+Pupw=,tag:NjdgUk4m0+b3L9Z2zohk4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
