apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:B7VBmYA59rSME0CgY6MwHXDYJYkZVOkg+SSOguiBe1ewN4+Qzo7kwg==,iv:3TCvm74e1sdI49zj3H2SWqYtZCW/vUBNNZ+L5FI4428=,tag:TQlNTOgjxMVR7jLv8a69gQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMkJKcXpvd1ZjdHdUTGNr
            UG1BRHdpQk9hWVVRMGdjZXJiS3lDZUIrTkFjClk3UytHWkhUQWJCU083ZDNpa3ox
            VHpDZ0hHQXFBcXkzbTc4NEt3T3FwblkKLS0tIHl5SlhpT2xZOEtPTXF4b3lQTUtD
            dGgra09TTG1yOFFjMkgzWUFPTEg2cGsK8Z88iRu3NmfUHZiX0UKaF8HBP7hoHhpG
            d3MOuM5qWUvWaHMF723xZuJz9W65r7A+KtxHS9JTjsIThxEOmTJ0zQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-29T00:51:46Z"
    mac: ENC[AES256_GCM,data:7Ff7UeGO5d1yLMN2LJoJhyknAuuir+CkdJTno3bgw040Orye0WfJ6wv5GjR89HAbOvu3UoSfZNdOTMBp4jC0Rz10Wm45xdUblWXuOy4qqnCI2PJ5hwyOKpJenPoummhokFWbpQUWic3ike4o46kbAaqTxq0iNpl8YcIq7EVwoZs=,iv:5DmtpLoIsqTknydytzpDOiAl4VKsrz4brRU5EAQv+KE=,tag:ox5uEtjZW3jeBZFnn8eyNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
