apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:f3vXUIo1/yofvArWNEaqHqsM94nf0plOvjpU448/UksME5p+9ozx2Q==,iv:coDHbh5QUGNJGqCx7Cn5N6yGpEOi7yb9SpOj0KMvpw4=,tag:MNz+Is0yBFDlWmKsN3r3KA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5M3QzR1pXdURsYzY2OFJq
            YU4rb1JUSk1hUnBIejZtKzc2bVhaWnlmV0RVClFDYm9XTjg3MWtEVUNsLzNwR203
            S2N6eHFZOXdOM0xwVVM2U2FzeXY0cHcKLS0tIFZYVlNGNTV4Wm9tYXJSb2lMOTFT
            bi9oZWlyK1AvSFlZRHVscXZFRGhNK0UKThsE7GhqBXgLhYQwRZJg6rUMX0dhxmmw
            Mtv8U+ui9BBhmmqprHfse7lJwu/Pft/I/7FPC8+hWQB2KyY4o4FIUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T04:23:03Z"
    mac: ENC[AES256_GCM,data:GhfTQa/bDxNXqgVZnPsuMt9NAslJfSy68WoHApPN2y8Y/KT66XshhH7arJP5QsHEeQPL7nyRkUlLwLytFQwR9tBZugmFocEWHI6RXL26px8I8fETKuYLjbHaeEQG8PDLBlDqvXDhjr/HAt9+SRui84A2a9/jYKxFYQbPVVeAAIU=,iv:ydveFQ0VX0675wMP1ujZQUZCCDG36Nw0Oetnj5GC15k=,tag:hZREJPCyE8d0c+FAAD3LtA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
