apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Dx9hC5Ew2cI8h9U27zBpEGWXuI8nV5IX/l1p+7MLkEvqDNAXGJJrNA==,iv:nPf0Vkw8o/jZ70GHoa5GpT28wtusxGrOzaOKPjeP9RM=,tag:5JIp+Gzel3e+qFJUB5LPYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTThXd3BVbEkvYmhkWm5B
            MGEwWno5WkhpMVNsbDc5bTN6cDVEZWdEcG40Cmdyb2VUUUswRGlVTGdkR1FKZDln
            Ykd0MWd6Rjc5VUxBVG9CZTBzTkZVamcKLS0tIHA4L044RzMwVTJMY2JkRGZWZ3Nz
            V2FFOFJZNzhrSzUvSXpJL21yeG4wMkkK5W00VYwaBicJKLsUpt/mQZcaZ1MFlrwh
            u2iG8TZfIOFVvbqOodWtuTF65fS04PZyD+NpznrXG6zxFN43ywdkIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-29T00:51:46Z"
    mac: ENC[AES256_GCM,data:GdolO7VTQ1URzbKnjbnQbZEtIFUQDa86eQmqR+x2lIEjT3freeD5nWiCNt1MRfE0z6jH0RvtLnMfxaWc+QXBcBr+wdP9NPxJylpsr1rChsqfy05SqM52wR7KPkdtNUBiX0MNChKLh0pLNY/FHdrRPQFbE3o5G5niJ3Q5aIOqqII=,iv:Hmdbi5E3T2yIsvu85BSi+kfV4c3VmuVvCY6ydU6mHU8=,tag:xK1WEFrsMutks3o9TYacQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
