apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:npqC4XP+YlT/utD+FzFoMus+0asDee6T58GKktS9O8dTwPTxOQknng==,iv:G/fSHwwQiRtYG1Lnny0CUiPHCsd4waDJBquPXT1WV14=,tag:SvcJPcpukfahWZn/aRgkNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsc1dHcmg1TmlFK0haYXMy
            NmpOOE9VR1FpV1dsKzVGUzdjTC8vSndkVDFZCnJYTEJ3ZHd2amExbkdLcVYzWm1y
            MlM1Y3NaQzhJN29kcDR1ZncybTZrYncKLS0tIE1ZMEt1QXpvOWE4d1dBNE56UmNi
            aVJQYU4yWnBZT3BaUVp5SENHUzNoUHMKIifX+4YOjbgUWBAdXZeHT7clhKDyjRI8
            Sf7PSQl1CegES1m/g9PgxAT+DaGej1W8d2m0o2za8Bn/aGamaLMfvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-26T03:58:59Z"
    mac: ENC[AES256_GCM,data:ODpvzECH/T/4Bjed2vh5BZlV1/atJ86leEnIbp9CQheSGDRCG02TVmJyWMMT0qHd4cYbAMEzozWXNHr+FXZfuBE8/gaKqH3jdbS+wo7SERGKEdnuI17Llqxr89/74+MEiDiWAa/zIMTnW9teYOnvMhols7n/2RwZBEcjf8NLLsM=,iv:P7pQU4iTUHT3+iG+e0bL/w87OLbBvQJ7UY+Z3//FM0w=,tag:S+zqEuOUuh0z0xsVmtthBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
