apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:vbWey0zsgEvtCvc49Ufv,iv:kzWPUDxUOkOVXkdCoza+/T6zUD8Y3L/GG5g5JFkP25s=,tag:522zlFGcTXkt43zZyWaTig==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:+ouFD/ICalhPMOhCv5cac8vJ9EHrSGS6URqbK6X0fDthFWIu,iv:Wi93EankQdT5d3V7FqLJPHJKkkuiLVBmmcec9gPwKVw=,tag:BO+rVEIViR8LdNOMDz0SAw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:YQWV6kNl//19,iv:pOeluEYBvU1H42eULkV3y7ZjFffeUIvaqW+oRxypZmQ=,tag:rCXrUcsgokUbcUWW5QlLaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUDhQNk5wbDY3b2MzUTNJ
            ZmtsZm9nQVR1MzREV2tmcmdqc001TVJqNmd3CnBSZXVQdXdvaWphQUl5alZwakZ3
            Y3FlR3Q0UG1IQUdGYlNLZkVlb1FJRzgKLS0tIHlyZkhWeXJwVEM1SjUzRS9zRWhU
            WWJYYVdVNE8zaStubWlvdGROa1lneVEKTbLMrBVnWMgnoKAqraZ8mH08EH1Nh7Y7
            gRa/GhlsJ3YIwc/HynXK+NCtAcqea9Vwvye+nxnp5oImTjkUnvQTlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T04:23:03Z"
    mac: ENC[AES256_GCM,data:zLdD5SD3P0sSCBb0Mvq+MKA6YLQqKPtxrUXKXwFZEKnhtDApAu9LRgW9oJXZcXKvBV4S5vVypKgsPJ0SRIjGbfOmWLfJ4ZL4A3kTxtlR85c4PfkmEZXTBE8Kn8q22QMvwZ1+eSaBUtT+dw8xXSU02uDKKRMUVFdapFpQYfonno4=,iv:vZ3eZBrRgRf/COz3QeLj6AOij5DFVJf18G9eGrkfx5w=,tag:tqO/euQ6oZJdpb9d5Fpniw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
