apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:AEekKzYY8w7vpCQX,iv:zeFPd6NBGdxXJlJhpawqv7aQ0UQIVlfMf9tXACwCnMo=,tag:TfNXG+xqEac+i3ashdp9vw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQnNOZDZ2Z05NY0pTaVdu
            aTVkZWhQUzFORTMvaC9Dd1dKRUdnREtsSVVFCldqaGtlNmUvMDZaTEkzcFo2OWVh
            MEI4L0NZemJ4UmhXUDB2Yk5KbFFBMTAKLS0tIENxbkVnTmNqVTRsSWxNckFTZDJl
            UUpVK2dHR2lmN2RVb2Y1eUs5SHVwNGsKUna699UYbh0ZGvs6xvDdHtSK60hPC8n2
            HFD1Q+YHo2Vb2T61YCYz7STIGYXBppgLgcSevhHJVvic5Y0ab4r9pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T04:23:03Z"
    mac: ENC[AES256_GCM,data:YQhskYI7+xvr/2ik8XDAPoP9C50JH66bnPYQkZPP8Jis39CtAhcn+bt88Ef6liIQbPmuQIDWxMtykE8GhE2K0GNclmIpZMVuf9EB2k5jTTO1BSIR61PoOSNmL5YNgkpxvpZFwv582jEi9IJH56xPyyvnbog3yvShXPSUXxTtuX4=,iv:Xk3VrS/T/1sNqA4mJftAs/UvAxCCrI9NPr/McWB/ThI=,tag:qMDYo+y8UWarnc6Dkfriuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
