apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:Ly+UJF5P8opwGLsP,iv:3gEEq40utf7bHxKfmwI9J1CuiFwkHiwyBwam6fI2cow=,tag:5JsAQzwlNoi6ovzdINIZwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzS0dJZnllZ0RFVHU3S1RB
            Q08xQUVlMktGVGhFaHAyZXQ1MEp5S1R6R0J3Ckx1VWpZckJEKzNHVWNaMHM2QXNU
            SkhMNnVSY1VnZFBDdElESnhXNkpIWXMKLS0tIHNTcytMeHJtV2hTMFkydlhxTFJ3
            YVNnMGNEVUJMdUNra1JJM1MvS3lUNUkKY7pwbe3mpyIQOqHeCYnZaj2TRsg8fc/C
            9dJNTxw1qEETI0jCwDGW6FNsQSV7Y6JyhNcKppELYtOVKZB0cHH3mQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-26T03:58:58Z"
    mac: ENC[AES256_GCM,data:J+7IkQMV1Ffj33WVITught1YcBRc4W6sIzs5omEefyh6/weLkmEDJVhmwmikNNIkZBcPurmQuJxPnv2hRgnW8UCYgNy44sz1UkidKFzifBF9OoUGFrwz1GtRHVrzAuCzpAc62R8cpymEI1GfTVgMy0G/rDDcL4woQqPJgqFifM0=,iv:qi2LnT1XMTJ9oCbDq7xwJnZUMy4kTE7HffJaHtWz4oI=,tag:G686qkbPz4wKhR8e3jAqkw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
