apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:tRYyZdJLAJg6Px6n0KQ=,iv:M2N8gTbBp3m3wztkf0vDNqNXoeWcj7T6i2Oo3i9Os7g=,tag:0Y7UHarXRXpJEx0rALMx0Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:C3B8DTJcqzCLBQ0Jt2Dn1Kiv1EpkQR/LE7tJbMjjzCwYDq/T,iv:J9/tgvJjCH80/UrUeY2oZPz28lqJp3XO+9HG2iriG8o=,tag:94s+mu3YzZj49X7xbYTSxQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:TcP25DFaw7Wr,iv:taJRAfhQAUGVql5BJ9p2wMwZAxQ4FDZxRPM2N1dO8Bs=,tag:K71Bn8rT2LbMtjAp3DAhfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YVJrNmxKZFhsd1ZEQ0ky
            Z0t2Q21jcjJqMGN0d0d6bG03em5ha3ZHZ1dBCmRwOFpSWXIvZEhJMjlNc3pFL0Q0
            NktEN0diVXdRdFVDVVhaQWlhaWFHUVEKLS0tIGdiS0ZJb0lLUmI2U2RSSWN6bDlo
            N3V0dWdjYktjUERkWDdOUGZBY2RrTmcKqDcrbsCur8LThic93P8Q99EZgKfzCp/X
            lCMgRoPL5u9kfTja0EwRqfDauCVSMrMaYZIrcWrrPNgfhrYQ5sgjfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-29T00:51:46Z"
    mac: ENC[AES256_GCM,data:LnX0wmvBwnPrdpQmvme6b38uY6rAkEWWT9FnI8qhBB2wGgSLoUVinrJY/u07oALHTBlw85v8oE7ITmQjJ/YvFlA80m2WtYd+xl6YANDUBTWqvZT0PRTKT+ua0vapy5DH+vk68OPFt/YC+mrR0qBL4xEJXAoT48C8n9jwGLgjUMc=,iv:ym1hz7+d1TekBtzqVmwq9ewMpNwshxUS20HsOpFAw3E=,tag:bXNvLHbhoE0jgN8FZ+5xsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
