apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:2UM+Zk9O/HgJk9tB,iv:RHqSaXdEDYfDj4g74lbTjNNuUP6xYwI+1Jo8gkAyTaM=,tag:ICeEQVnhdakACJZb4+YVRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUUE5MFJ4Tk0vV1N5cDJl
            QVFlR2JhaTRYNDhFTnp6VCtoQXc5TFBCMmdnCndaUDY5Q2VKY2FEaDNlUUt1NDJG
            cHE5TXQwZ1hXbFhwNmtrVWhIMDZlQmcKLS0tIFdXWElDc2dZekZ6TGJCRldpTWxz
            di9aR0RTK2VEZEhwZ1lFNjVwTVovVHcKuqc6wIErZsg7HQJRc82m7kVfZhOzOrdr
            rMRwL1zqJigYFJprJLB61xho8/qx+tbTBJ2+jMGG68vx0uSm3FqifQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T07:10:26Z"
    mac: ENC[AES256_GCM,data:NYFVYJuWXHyahvfZDgkZKby2okMQsJJeYo9IJdnSsvwTiKQIblod1559p5jSjqM6lFLbChkHnY/XJJLStqlGnuS1/ylHTK8flYSbXZODwIwHQ34tqYIUzvdcRiOr9p1N5zpNTaBaZesqQo0WtIglWMlEykF+H0X59U0X+8ybWSc=,iv:pcnSWNzDEFIMEJsHUEMWzlCl1LZ5X1YWbeEzYIyjhLA=,tag:g4K0JZ2O5dTeROvOQNks7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
