apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:y+aHqTzqhFJ9bpnUNLoc,iv:3zu9QEMWHB52iUywMte19+KtciTNXNjAeJyEa6bgTzM=,tag:3qo+AVHStxC9tb9nTBdVRA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:0OTR9f+QCCLSut57q+Z8TDQDfWRWXbE0Mo4cafT3wb/Sx4Px,iv:RuQC4xx11JLxEgW7UIIwlEB7BmyAPG4BaAJ/YsVyscs=,tag:CVasKn37qAXsRRmWAhXfaw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:Q/Ta+R/+PF51,iv:kVVuihmtgsK/s2McA8MiyvQB/bSFjQ/6wT3OGYBn/so=,tag:TGS4JjZSigk6M2ufCnTUNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhekZMU3YrWnljVWhwU1Ux
            VkxDZk9Uc1Yyazd3ZUJRelNjT0NqN0R1SWpvCkFMUHNhY2lzb0tlL0lacUEwNzRO
            azh0RHRtc29QMUR5b0UzQTlqRzZBaWsKLS0tIGkvaE9uczRCaWNiZ2FVZkVxcmlD
            cUVEN1VXdG1lSzh5ZzN4SThoZkV3VWsKcCaoLBtbPrVn0ZKH0PomVY6jWWlBMp4m
            5wpejZtk0R+/ZCKUj/rGRbvQYctQcqKSMWNwgMuI0iq2ZhzYm/eS7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T07:10:27Z"
    mac: ENC[AES256_GCM,data:KRcfGVFEfaQivCYO+US7LeyC8H/a2CEQfTvFNNGRX3GWI4VXuuEwVbfJ0Md6wljKsmW1ntZIBg2CIVBvm+yLIIyy7W0q1tDff7yl0nbXA8vaWo2lkExt+F319IB9C8TGELTIv8YAjsnfrddZfQUHde/NngpqUFcZzth6ZBDdtuk=,iv:k33VNhylr3Ch6aT9KrO2innR/TdW9eCgHzcj4Zk70kE=,tag:AsK8s7RZdwp8Qejio1dkcQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
