apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:mAKu71om9GOix/Ust7M1bSAJzga/7pPNydmA0g2pWvv6ehmL,iv:BqkaUx8uwP5mYrSUPedtcB4LZ5Y14vG8J12NpxPZ0V0=,tag:uu+7Gb856uBJArg6hLI9Bg==,type:str]
    credentials.json: ENC[AES256_GCM,data:jk6oE+nTNGvpaW0H6JdB7bo4F17NAF6j+xVRKs4ryJf4RQgEOecmydGWgB40z2i1LYAQuA/wOA+O4B6BCdItVoKnLJSjVj8ypvM3Z7nHOgcFtRriMw0HaUUOaLGWbI0h6Ds9Jzfn2+Yk8fWWif8vuyAlZ3uqcLLLMJZjtYkW2Pe+YBvBvBCVzScTkMIByEJbmQeJzOnrBiF/eJh1EY3TykLCYoGYhRySGRCWD1QP5w==,iv:4QXlTBY+vEtZaQvTKq6YnZEvsJb9KOqY7pzDhegXDMc=,tag:LcIrLCBXlfC+xid2OM3w8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXS2ZPeW9Wc2t2T2Q5Z2t0
            M0sxNWVFM3M5d1pWM002MC9MNXpTREZobFdjCmpQUHBBbFArcEV0TUJXOXpQT01H
            UzVqKzlRU29XWGQ5aXN3SERtYzlMdDgKLS0tIHFrcmJTZVNlb0pPaVg2WjRqVFla
            M3ZGUFFlenl6VE9JTmljenRNNWs0U2MKILRNzfC1KCX1h6SFG8c9iawdUoXnk3az
            wbJtCxEvPFgmeyNoIq5FdaMHH59EkFjxrNfGQVsGwAzZxNkc7u5sOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-26T03:58:59Z"
    mac: ENC[AES256_GCM,data:Z2iIn+Q8AO5yI6kCrFACMDuxSuUICVgmJiLCu5kHSADiN/3APUetY8Pg1j0qcQ+kDe6hyhTKLLr8qV4GZbuc4OZJwRscrikoJ4FvGQWCkFx7/0y94tkSq5o61OTty5Fj8FlEoLgMA7eqrjLWHMMHDVI2SAPmIo0AlhBZdbnO7hw=,iv:t3ZB5X22gW/7dtkqpzBWs+3deNg1mw3a+h7LwM5gzNw=,tag:/njb6zDzXQzMPKXIsEwXvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
