apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:nKWd03THCvS3yBfWyXMemV/ry+SsvhlvunvQwQ/2866i5eWZ,iv:GwPzfLcR7Op/OhQjUXv8LvV2g6gJ1oY3kDSv9QlzqnY=,tag:/s9Qj+mMQURRGFkDSOQ1ZA==,type:str]
    credentials.json: ENC[AES256_GCM,data:7CQ/QWZZhHJIXN3d2QYrY+NWAKrRDANAlxBGbR/6xcZyYFqZr5/A52LPaW567XasnSw2MNpfxIQoCeSqRIDlA03kPHhEqXs4ZTwMaR1mn5NJv/bpn1PGN6gk52tzYrrjmrfBKIAewtcHX0GQEzKGxsyCmbv+LGmPt/6cLWIpsQ1H55NaY8knSY1Ml+A1U5DNucbrgRv3GtHKEK6O3JyTNbdcjDd+BhRcQuIIo0IL+w==,iv:gMqrrbNVOorqL0KtB7a5ZCsdlzT2X8tLQX8sjUSChds=,tag:AkUV3GpysC3fLWIfikTf7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNkp5MzN1cTZ5UlRVczFX
            QnluVDhGWS9tbDJtNHlWVDdxeHY4c1M0VFdBCjF3RlBEZEwwKzJEbVVhZEltSFJj
            bmFyWHlUMjJWNjJFYlJMZ3d4YmFLSVUKLS0tIDN5OXc4ZmJtM0UwanliWEhNam40
            RkFIaUdCSEprQ25pWndLWjVqUlAvNWMK+6iSOXRj30Xsfdo/q0VVr+0gjzGjy5rN
            bTHzxjBcNulywPgdc/IyrsCo6ZdFxLfeULKNeQZ2xZNQyBUupb2N+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-29T00:51:46Z"
    mac: ENC[AES256_GCM,data:nuaL7RUoinvsHoNtd7WJfczn/lvFGFGpdbfyMysWULjF6s3vV0AykBwuLkK6ji37bcGjBmFcrkxGcD2KWGDyuCKkbkgxZ97yIL5bKsTf46aKclt0O3Ulz4oPwxvVLd6Cwd8uHsrCkk80MCWgq1lfOv2tPlMtT6QultTNHqqAQQs=,iv:8/fAGSLQklNuCrl3sT7+3cSVw/OSyj1DR8AVIIAplUU=,tag:BadG2OuzmsTd+rxaSWIdNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
