apiVersion: v1
kind: Secret
metadata:
    name: pgo-s3-creds
stringData:
    repo1-s3-key: ENC[AES256_GCM,data:uPfyVAr5VRHGOjBPhIO34UQpMbw=,iv:ZV1/ksEIghPYuZPzyt60tE71G/U4B/Cm98ZI9EFtOUk=,tag:tvdOeLYwrzDHtEVf2Ooo4g==,type:str]
    repo1-s3-key-secret: ENC[AES256_GCM,data:o506a+B4KmGWmICa4668775FR5FqVsBIvIsZHwTUFXDdkC268+BRdw==,iv:QwSGOFxB+htoY1eaM/cgw7QqrbgAwLtILpt+acL4x1M=,tag:X8bbpPbajJw/Xl00lD5hCQ==,type:str]
    repo1-s3-region: ENC[AES256_GCM,data:Fj3XuKsThE3R,iv:6rv0xqP2NZsciv+Cu0vckuiaJ+wJcJvZ/8UmiJzSBDI=,tag:GeJJwxsAlzxKAqdQGVsA7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNHFkb1VoNnpqWVNFRjhS
            a2hrZzVtTVRBa1VRV29PcTRldHdJU3Z0NFFNCmdMQmptdWlkV1J5TjM1VDhUTXY0
            ZTFjdzRCWU16T0VtcVFMdUxIUDAwVGcKLS0tIForKzVvM2xzODlvRXdtRzd2YWJj
            Uy9zQ3ZzK0tpQzBXL3hGOEJTMDM1YmcKvTOhg7QymlmkF3vRPeqH0jXMM8LL5L7a
            5PZQJxqqEBeTxrAaheTSDbN+bOuOLHx/T7WMcm8rdKphz7+9GuxNYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-08T00:59:13Z"
    mac: ENC[AES256_GCM,data:VxwCUvoEbSqQ79MEi8W2t16BDSjGjHzGI4AsZDWZcdXiTUKtCzhEZUVwzJzR9zb3bbZgljcnVFUWesKjd5MtfnI5OrzvKUaVw4tgoCFq9p7s2oJXPA1HNpQZgRW5ItGXGrpHDVzW962VxH8SUYMHKfjlQcN7a8aC1c2pCcno1to=,iv:IYMs5lsC9KMyFh1P/lpwhg2B7abQAORZu2UXKRJ/ycI=,tag:wGAd8BBpAteHxrMYHuIlzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
