apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:ZkELmp/I0mT6pOQ5DFYiDl7hTeg/t7yMUKiJZu69jRVGIIJtkdCGEQ==,iv:D4ox5xTEkI3lQM38AvAodW94fG12Moecbdk7BDdagYk=,tag:W7zOIIz05sDBbLtdXaCPKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaGhQOVQxNmlXOVZ1SkMy
            OHJxQzV1QnBCdkNuN1pRQURpb2hyUWhCQ2prCktVUk9kdWNIL2MyVmQrK1M5SzN5
            QStzcHRCQ2R4akRvNS9OcTF6eUU5cW8KLS0tIHAzbmVvanQrMlpPNVN1a3crYksv
            TlB0ZVJ0RXZuaTJUck1Jb1M1K0VEMVUKzh0yCaJtv8LlUKs89+iwhvZm9vX1Nh66
            QJOSBGUE+owxFgiDN/wrVOPozmIJ2l7moEqZC5Ory5VBJTBNlaH3fA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T07:10:27Z"
    mac: ENC[AES256_GCM,data:KKbvRf4JUsAn+/rqHFFjq8iAwNavU0RGMw7t5Ulhhn8YGT0d0d3gjz3gcQmhOrmZeVs0/3W+71DqGNcdIK9UEFEgd1xbh8w+GNLBNSlU4SHZZbMjocAZh4ocMGFIORWEeLUEQHC5LMI9d3n3JcaTCAGnC0aB9+ycwboSJChvxps=,iv:a8JYwWyO2tqBimveAIWDU7xcoqsBc4ilfMFghLUi4V4=,tag:1bCpDe593CIeV+xu6jByNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
