apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:V8Du/CIws9E9KAM3X04A/XkA+haytNZh9ikwuIfBEgysAzbRsnY1aA==,iv:QbtDVOQKzy0I0ybuwGG37UTtzRjMghvZ31oQs1V5s8o=,tag:Q0oZUgpj70aLPb+wltAnhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10k24ecztrqjc9w9ucdc6n8m3qdnxjw04j3re4lnh7233mf2fsv9qnzt26l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNHF3cDZlY1AyNWFSYkky
            NTZDTHM1czhuMzdyUDU4eUU0Q0tmSTNpdFE0CldnS3hSSE1aK08wc1VwdUR4UXNN
            WlIzU3dYUWNia01QSTBYZmRMNWw2MGMKLS0tIC81b1RKTVZZeC9JNko1aFhjaExG
            ZlJ5Y2Z5cy9STVdrMzBacVpnSy9ZZ28KuO0Z64Hu69InOF11xmByFmD3/dgwUhDA
            sSuB7/yDFHK/FHC64ySZtpnFwwUokSCs8/SWZoAk3D7svLuFgmOvpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T04:23:03Z"
    mac: ENC[AES256_GCM,data:73OELMf5e3RJc0vqSaQRqNBCoFnORt5xVCL6CaD1vdbaAb7nUvMfBsqu02KCDdgKRYGUXP4o4YFy/syjd79I+nCVflU4ne/tygJkSWRV+yWuHpdDWlNPYRag+4IS18USqAmR35cf9p7JoPLyCHgLFKHnwfQ9Hc9ZcZ6DzKHNito=,iv:TOzP0V2qFY7RQv6H3Wdyx7tyvJMgOdUaEV9MNJmRZh0=,tag:ecBWHVaMxcxY1s3+eBxxDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
